/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.3
  Forc version: 0.67.0
  Fuel-Core version: 0.41.9
*/

import { ContractFactory as __ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions } from "fuels";

import { KombinationToken } from "./KombinationToken";

const bytecode = decompressBytecode("H4sIAAAAAAAAA6VSMWgUURCdPRdcLWTkrvoiLnIWBpJscokcpNnPZtm7nMf9MoWLv7EPZzgEEVLaCEZQU6a0/NdZXpkypeWVBgykEU5SnG82e6CyVllYZv+beW/eznx1EdE+kU/Fc+N9GY/z+cTj+VxypH4YOiTvZBjTzvNz8lRsCTHKMxflifOGHQru6Saxbgi+DmxdnRGFsxbtXk5r5nLqQ+cd+F3kqeSvoW4NGlTw02bM2o+Bt4C3KvhvVHIqvA3kN0zm9vB9xyRuZjUHJhsbm1JgkrGB5lKeMmq5Ld+FfqdxwGnjANgSsDbiCjh7ec+tmIGztg+ujoJCK3FsdcTIO2iyaPzJB06Co9cu6hHdUREzF5Y4+MX5VcFP3EPpZXrOwPNto8NFn8jqUPoseDgz+l14nPLE9Max7QJHhEfMhoPhNvmIt6D91qbwOHBf4J3VWfTvvBKZF/JfbZ+r8ltqcEp17U/qfdkJ0egpPYCnb+KpYv7b5fw3UfNdfFbUbJU1q6g5+Y/O/bJmGbPfxGxWMd/lx7p5dxRTDXfk9RN4ET+P8H4kuvkpuLqDKjkmlU1pBEx2Wu+G8ahDtVyT3FPv2VUk9RPvL6Yj8D6jdmf2t84hUXuhhZ2wzNieYw8J9ofdy16AY0dhIPdb9D4I55qaiKJX+KvSy+B9/8VL+YXy8Wa/ARAS6QmgAwAA");

export class KombinationTokenFactory extends __ContractFactory<KombinationToken> {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(
      bytecode,
      KombinationToken.abi,
      accountOrProvider,
      KombinationToken.storageSlots
    );
  }

  static deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ) {
    const factory = new KombinationTokenFactory(wallet);
    return factory.deploy(options);
  }
}
