[project]
authors = ["vitor"]
entry = "main.sw"
license = "Apache-2.0"
name = "auction"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.7.1" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.25.2" }